name: pixelmonworldsweb
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.5
  http: ^1.1.0
  go_router: ^6.0.0
  shared_preferences: ^2.2.2
  webview_flutter: ^4.0.7
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/pixelmonfoto.png
    - assets/minecraft_title.png
    - assets/minecraft_title2.png


  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
